### ISSUE TITLE
Transformation of Dino-normalized expression

### ISSUE THREAD

**Issue by mbernste** [JBrownBiostat/Dino#2]
@JBrownBiostat I have another quick question, but thought I'd open a separate issue for any future readers.  Would you suggest using the raw Dino-normalized expression values for downstream analyses? Or would you suggest computing Z-scores (or log or square-root transformation)?

I would assume that the raw Dino-normalized values should be used for DE analysis, but am less sure about other tasks such as clustering or visualization. I am finding that when using the raw Dino-normalized values, clusters tend to look less distinct then when performing some sort of transformation that stabilizes the variance. Because Dino normalized values can be interpreted as "latent expression values", which vary by orders of magnitude, I assume that such transformations make sense? Maybe I'm off base here. Thank you so much again!

**Comment by JBrownBiostat** [comment]
You are exactly correct. For many downstream analyses, a transformation (such as but not limited to log with pseudo-count) of the normalized expression would be helpful.

For context, since the normalized values are sampled from a posterior mixture of gammas, the lower bound on the variance roughly scales proportional to the mean, and so, just as with other methods (and raw data as well), higher expressing genes tend to also be high variance genes even post normalization. These genes can and do therefore affect various analyses if an appropriate variance stabilizing transformation is not taken.

For the question of DE analysis specifically, the issue of data transformation becomes a bit more context specific, depending on the particular error distribution you are using. Under a t-test or simple linear regression with Normal error and constant variance across conditions, a variance stabilizing transformation would be appropriate as otherwise the model assumptions would be violated (see above). Likewise with a test for differences in distribution, such as the Wilcoxon test which is popular in some packages. In other cases, such as Poisson or Negative Binomial error distributions, possibly implemented through a GLM, it may actually be more advantageous not to normalize the data (leaving it as raw and un-transformed counts) and to, instead, account for differences in sequencing depth through sample-specific model offsets. There are at least a couple packages for genomics analysis which do this within-model correction by default if this is of interest, but of course, you still need some way to identify subsets of samples/cells you wish to compare before running such an analysis.

**Comment by mbernste** [comment]
Awesome, thank you!! This confirms my understanding
